const {MONGODB_URI, TOKEN_SECRET, GITHUB_CALLBACK_URL, GITHUB_CLIENT_SECRET, GITHUB_CLIENT_ID} = process.env;

module.exports = {
    env: {
      "MONGODB_URI": MONGODB_URI,
      "TOKEN_SECRET": TOKEN_SECRET,
      "GITHUB_CALLBACK_URL": GITHUB_CALLBACK_URL,
      "GITHUB_CLIENT_SECRET": GITHUB_CLIENT_SECRET,
      "GITHUB_CLIENT_ID": GITHUB_CLIENT_ID
    }
  }