const {NEXT_PUBLIC_STRIPE_PUBLIC_KEY, MONGODB_URI, TOKEN_SECRET, GITHUB_CALLBACK_URL, GITHUB_CLIENT_SECRET, GITHUB_CLIENT_ID, STRIPE_SECRET_KEY, CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET} = process.env;

if (typeof require !== "undefined") {
  require.extensions[".less"] = () => {};
  require.extensions[".css"] = (file) => {};
}

module.exports = {
    env: {
      "MONGODB_URI": MONGODB_URI,
      "TOKEN_SECRET": TOKEN_SECRET,
      "GITHUB_CALLBACK_URL": GITHUB_CALLBACK_URL,
      "GITHUB_CLIENT_SECRET": GITHUB_CLIENT_SECRET,
      "GITHUB_CLIENT_ID": GITHUB_CLIENT_ID,
      "STRIPE_SECRET_KEY": STRIPE_SECRET_KEY,
      "CLOUDINARY_CLOUD_NAME": CLOUDINARY_CLOUD_NAME,
      "CLOUDINARY_API_KEY": CLOUDINARY_API_KEY,
      "CLOUDINARY_API_SECRET": CLOUDINARY_API_SECRET,
      "NEXT_PUBLIC_STRIPE_PUBLIC_KEY": NEXT_PUBLIC_STRIPE_PUBLIC_KEY
    }
  }
